# Generated by Django 3.2.6 on 2021-09-21 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_bloguser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloguser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
